"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured


BASE_DIR = Path(__file__).resolve().parent.parent


# Security
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-6htx6!csi5lpu9p850zdw#_*pfj)-a)2$u&jetg#@dm@%i*&7-"
)

DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "ALLOWED_HOSTS",
        "127.0.0.1,localhost,.railway.app,.up.railway.app"
    ).split(",")
    if host.strip()
]

railway_public_domain = os.environ.get("RAILWAY_PUBLIC_DOMAIN")

if railway_public_domain:
    ALLOWED_HOSTS.append(railway_public_domain)


CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "CSRF_TRUSTED_ORIGINS",
        "http://127.0.0.1:8000,http://localhost:8000,https://*.railway.app,https://*.up.railway.app"
    ).split(",")
    if origin.strip()
]

if railway_public_domain:
    CSRF_TRUSTED_ORIGINS.append(f"https://{railway_public_domain}")


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'resources',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'config.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


# Database
# Local = SQLite
# Railway = PostgreSQL through DATABASE_URL
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    )
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static and media files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

USE_CLOUD_STORAGE = os.environ.get(
    "USE_CLOUD_STORAGE",
    "False",
).strip().lower() in {"1", "true", "yes", "on"}

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": MEDIA_ROOT,
            "base_url": MEDIA_URL,
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

if USE_CLOUD_STORAGE:
    supabase_storage_settings = {
        "SUPABASE_S3_ACCESS_KEY_ID": os.environ.get("SUPABASE_S3_ACCESS_KEY_ID"),
        "SUPABASE_S3_SECRET_ACCESS_KEY": os.environ.get("SUPABASE_S3_SECRET_ACCESS_KEY"),
        "SUPABASE_S3_BUCKET_NAME": os.environ.get("SUPABASE_S3_BUCKET_NAME"),
        "SUPABASE_S3_ENDPOINT_URL": os.environ.get("SUPABASE_S3_ENDPOINT_URL"),
        "SUPABASE_S3_REGION": os.environ.get("SUPABASE_S3_REGION"),
        "SUPABASE_PUBLIC_MEDIA_URL": os.environ.get("SUPABASE_PUBLIC_MEDIA_URL"),
    }

    missing_storage_settings = [
        name
        for name, value in supabase_storage_settings.items()
        if not value
    ]

    if missing_storage_settings:
        raise ImproperlyConfigured(
            "Cloud storage is enabled, but these environment variables are "
            f"missing: {', '.join(missing_storage_settings)}"
        )

    public_media_url = supabase_storage_settings[
        "SUPABASE_PUBLIC_MEDIA_URL"
    ].rstrip("/")

    STORAGES["default"] = {
        "BACKEND": "config.storage_backends.SupabaseMediaStorage",
        "OPTIONS": {
            "access_key": supabase_storage_settings[
                "SUPABASE_S3_ACCESS_KEY_ID"
            ],
            "secret_key": supabase_storage_settings[
                "SUPABASE_S3_SECRET_ACCESS_KEY"
            ],
            "bucket_name": supabase_storage_settings[
                "SUPABASE_S3_BUCKET_NAME"
            ],
            "endpoint_url": supabase_storage_settings[
                "SUPABASE_S3_ENDPOINT_URL"
            ].rstrip("/"),
            "region_name": supabase_storage_settings[
                "SUPABASE_S3_REGION"
            ],
            "addressing_style": "path",
            "signature_version": "s3v4",
            "default_acl": None,
            "file_overwrite": False,
            "querystring_auth": False,
            "public_base_url": public_media_url,
        },
    }

    MEDIA_URL = f"{public_media_url}/"


# Security behind Railway proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Iframe setting for previews
X_FRAME_OPTIONS = 'SAMEORIGIN'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'