# Generated by Django 6.0.6 on 2026-06-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='resource_type',
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('SLIDE', 'Slides'), ('NOTE', 'Notes'), ('QUESTION', 'Questions'), ('LAB', 'Lab Files'), ('VIDEO', 'Videos'), ('BOOK', 'Books'), ('LINK', 'Useful Links'), ('OTHER', 'Other')], default='LINK', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='question_type',
            field=models.CharField(blank=True, choices=[('MIDTERM', 'Midterm'), ('FINAL', 'Final'), ('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz'), ('PRACTICE', 'Practice')], max_length=20),
        ),
    ]
