# Generated by Django 6.0.6 on 2026-06-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_resource_resource_type_resource_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='exam_part',
            field=models.CharField(choices=[('MIDTERM', 'Midterm Part'), ('FINAL', 'Final Part'), ('FULL', 'Full Course'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='question_type',
            field=models.CharField(blank=True, choices=[('PAST_EXAM', 'Past Exam'), ('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz'), ('PRACTICE', 'Practice')], max_length=20),
        ),
    ]
