# Generated by Django 6.0.6 on 2026-06-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_exam_part_alter_resource_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='question_type',
            field=models.CharField(blank=True, choices=[('PAST_EXAM', 'Past Exam'), ('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz'), ('PRACTICE', 'Practice Sheet')], max_length=20),
        ),
    ]
