# Generated by Django 6.0.6 on 2026-06-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_resource_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='exam_part',
            field=models.CharField(choices=[('MIDTERM', 'Midterm'), ('FINAL', 'Final'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
    ]
