# Generated by Django 6.0.6 on 2026-06-23 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_resource_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(help_text='Example: CSE421, CSE370, CSE220', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(help_text='Example: Computer Networks, Database Systems', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Short description shown on the course page.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('SLIDE', 'Slides'), ('NOTE', 'Notes'), ('QUESTION', 'Questions'), ('LAB', 'Lab Files'), ('VIDEO', 'Videos'), ('BOOK', 'Books'), ('LINK', 'Useful Links'), ('OTHER', 'Other')], help_text='Select what kind of material this is.', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(help_text='Select the course this resource belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resources.course'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, help_text='Optional short explanation about this resource.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='exam_part',
            field=models.CharField(choices=[('MIDTERM', 'Midterm'), ('FINAL', 'Final'), ('GENERAL', 'General')], default='GENERAL', help_text='Choose whether this belongs to Midterm, Final, or General syllabus.', max_length=20, verbose_name='Syllabus'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='external_link',
            field=models.URLField(blank=True, help_text='Paste Google Drive, YouTube, playlist, or useful website link here.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, help_text='Upload file here if you want to store the file directly.', null=True, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='question_type',
            field=models.CharField(blank=True, choices=[('PAST_EXAM', 'Past Exam'), ('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz'), ('PRACTICE', 'Practice')], help_text='Only fill this if Category is Questions. Leave empty for slides, notes, videos, labs, etc.', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='semester',
            field=models.CharField(blank=True, help_text='Optional. Example: Spring 2025, Summer 2026', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(help_text='Example: MSMA Playlist, Midterm Slides, Final Past Question', max_length=200),
        ),
    ]
