# Generated by Django 6.0.6 on 2026-06-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_alter_course_course_code_alter_course_course_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='question_type',
            field=models.CharField(blank=True, choices=[('PAST_EXAM', 'Past Exam'), ('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz'), ('PRACTICE', 'Practice')], help_text='Only fill this if Category is Questions.', max_length=20),
        ),
    ]
