# Generated by Django 6.0.6 on 2026-06-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_alter_resource_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lab_type',
            field=models.CharField(choices=[('NO_LAB', 'No Lab'), ('WEEKLY', 'Weekly Lab'), ('BIWEEKLY', 'Biweekly Lab')], default='NO_LAB', help_text='Select lab type for this course.', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.CharField(blank=True, help_text='Example: CSE220, CSE221, or None', max_length=200),
        ),
    ]
