# Generated by Django 6.0.6 on 2026-06-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_course_lab_type_course_prerequisite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisite',
        ),
        migrations.AddField(
            model_name='course',
            name='hard_prerequisite',
            field=models.CharField(blank=True, help_text='Example: CSE220, CSE221. Leave empty if there is no hard prerequisite.', max_length=250),
        ),
        migrations.AddField(
            model_name='course',
            name='soft_prerequisite',
            field=models.CharField(blank=True, help_text='Example: CSE370. Optional course that helps but is not mandatory.', max_length=250),
        ),
    ]
