# Generated by Django 6.0.6 on 2026-06-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_remove_course_prerequisite_course_hard_prerequisite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
