# Generated by Django 6.0.6 on 2026-06-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_resource_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('BROKEN_LINK', 'Broken link'), ('WRONG_RESOURCE', 'Wrong course/resource'), ('REMOVAL_REQUEST', 'Request removal'), ('SUGGEST_RESOURCE', 'Suggest new resource'), ('OTHER', 'Other')], help_text='Select what kind of issue this is.', max_length=30)),
                ('course_code', models.CharField(blank=True, help_text='Example: CSE421, MAT215', max_length=30)),
                ('resource_title_or_link', models.CharField(blank=True, help_text='Paste the resource title or link if possible.', max_length=300)),
                ('details', models.TextField(help_text='Describe the problem.')),
                ('contact_email', models.EmailField(blank=True, help_text='Optional. Student can leave email if they want a reply.', max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CHECKED', 'Checked'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
