# Generated by Django 6.0.6 on 2026-06-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_reportissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='solution_file',
            field=models.FileField(blank=True, help_text='Optional. Upload solution/answer file only for question resources.', null=True, upload_to='resources/solutions/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='solution_link',
            field=models.URLField(blank=True, help_text='Optional. Paste solution/answer link only for question resources.'),
        ),
    ]
